version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: rails_tutorial_app
        # 事前に手元で/tmp/pids/server.pidを削除する
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ${RAILS_HOME}:/src
    ports:
      - ${RAILS_PORT}:3000
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: rails_tutorial_db
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ./docker/db/mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
