source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.6"

gem "rails",           "7.2.2.1"
# Active Storageバリデーション用のgem
gem "active_storage_validations", "0.9.8"
# 画像処理用のgemを追加する
gem "image_processing",           "1.12.2"
gem "bcrypt",          "3.1.18"
gem "faker",           "2.21.0"
# ページネーション用のgem
gem "will_paginate",           "3.3.1"
gem "bootstrap-will_paginate", "1.0.0"
gem "bootstrap-sass",  "3.4.1"
gem "sassc-rails",     "2.1.2"
gem "sprockets-rails", "3.4.2"
gem "importmap-rails", "1.1.5"
gem "turbo-rails",     "1.4.0"
gem "stimulus-rails",  "1.2.1"
gem "jbuilder",        "2.11.5"
gem "puma",            ">= 6.0.0"
gem "bootsnap",        "1.16.0", require: false
gem "sqlite3",         "1.6.1"
gem "mysql2", "~> 0.5"

group :development, :test do
  gem "debug",   ">= 1.8.0", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console",         "4.2.0"
  gem "solargraph",          "0.50.0"
  gem "irb",                 "~> 1.13"
  gem "repl_type_completor", "0.1.2"
end

group :test do
  gem "capybara",                 "3.38.0"
  gem "selenium-webdriver",       "4.8.3"
  gem "webdrivers",               "5.2.0"
  gem "rails-controller-testing", "1.0.5"
  gem "minitest",                 ">= 5.12.2"
  gem "minitest-reporters",       "1.6.0"
  gem 'mutex_m',                  "~> 0.2.0"
  gem 'guard',                    "~> 2.19.0"
  gem "guard-minitest",           "2.4.6"
end
